repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        args:
          - "--config=/home/boernerf/.pre-commit-config/commitlint.config.conventional.js"
        additional_dependencies:
          - "@commitlint/config-conventional"
